version: "3.8"

services:
  openvpn-as-exporter:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: openvpn-as-exporter
    volumes:
      - ../configs/openvpn-as-exporter.yaml:/etc/openvpn-as-exporter/config.yaml:ro
      # Mount sacli scripts for local mode
      - /usr/local/openvpn_as/scripts:/usr/local/openvpn_as/scripts:ro
    network_mode: host
    restart: unless-stopped
    environment:
      - OPENVPN_AS_EXPORTER_BACKEND_MODE=sacli
